# Import dependencies
library(h2o, quietly = TRUE)
library(Rtsne, quietly = TRUE)
library(cluster, quietly = TRUE)
library(caret, quietly = TRUE)
library(dplyr, quietly = TRUE)
library(mice, quietly = TRUE)

# Set working directory 
local_path = paste(path, "3_GLRM_Clustering", sep="")
setwd(local_path)

# Source functions
source('glrm_cluster_wrapper.R')
source(paste(path, 'helper_functions.R', sep=""))
source(paste(path, 'similarity_matrix_functions.R', sep=""))
source(paste(path, '6_Outcome_Profiles/boxplotoutcomes.R', sep = ""))


# Load imputed data
load(paste(path,'2_Data_Imputation/cobrit_imputeddfs.RData', sep = ""))

# Set seed
set.seed(123)

# Multiple imputation datasets  
data1 = mice::complete(imputed_cobrit_m5, 1)
data2 = mice::complete(imputed_cobrit_m5, 2)
data3 = mice::complete(imputed_cobrit_m5, 3)
data4 = mice::complete(imputed_cobrit_m5, 4)
data5 = mice::complete(imputed_cobrit_m5, 5)

colnames(data1) = tolower(gsub("[[:punct:][:blank:]]", "", colnames(data1)))
colnames(data2) = tolower(gsub("[[:punct:][:blank:]]", "", colnames(data2)))
colnames(data3) = tolower(gsub("[[:punct:][:blank:]]", "", colnames(data3)))
colnames(data4) = tolower(gsub("[[:punct:][:blank:]]", "", colnames(data4)))
colnames(data5) = tolower(gsub("[[:punct:][:blank:]]", "", colnames(data5)))


# create loss order list: 'Hinge' for factor columns, 'Quadratic' for numeric/integer columns
factor_col_ind = which(colnames(data1) %in% colnames(data1[,sapply(data1, is.factor)==TRUE]))
loss_order = rep('Quadratic', dim(data1)[2])
loss_order[factor_col_ind] = 'Hinge'


results1 = glrm_cluster_wrapper(data1, gamma_range = c(300:550), krange = c(3:10), loss_order= loss_order)
save(results1, file = "results1.RData")

results2 = glrm_cluster_wrapper(data2, gamma_range = c(300:550), krange = c(3:10), loss_order= loss_order)
save(results2, file ="results2.RData")

results3 = glrm_cluster_wrapper(data3, gamma_range = c(300:550), krange = c(3:10), loss_order= loss_order)
save(results3, file = "results3.RData")

results4 = glrm_cluster_wrapper(data4, gamma_range = c(300:550), krange = c(3:10), loss_order= loss_order)
save(results4, file = "results4.RData")

results5 = glrm_cluster_wrapper(data5, gamma_range = c(300:550), krange = c(3:10), loss_order= loss_order)
save(results5, file = "results5.RData")

# Find the intersect of features selected in cross-validation
final_cols_1 = Reduce(intersect, list(results1[[6]], results1[[7]], results1[[8]], results1[[9]], results1[[10]]))
final_cols_2 = Reduce(intersect, list(results2[[6]], results2[[7]], results2[[8]], results2[[9]], results2[[10]]))
final_cols_3 = Reduce(intersect, list(results3[[6]], results3[[7]], results3[[8]], results3[[9]], results3[[10]]))
final_cols_4 = Reduce(intersect, list(results4[[6]], results4[[7]], results4[[8]], results4[[9]], results4[[10]]))
final_cols_5 = Reduce(intersect, list(results5[[6]], results5[[7]], results5[[8]], results5[[9]], results5[[10]]))


# Find the intersect of the features selected from 5 MI datasets (all numerical features)
final_cols_total = Reduce(intersect, list(final_cols_1, final_cols_2, final_cols_3, final_cols_4, final_cols_5))


# Subset the final selected features from each MI dataset
x1 = data1[,final_cols_total]
x2 = data2[,final_cols_total]
x3 = data3[,final_cols_total]
x4 = data4[,final_cols_total]
x5 = data5[,final_cols_total]

save(final_cols_total, x1, x2, x3, x4, x5, file = 'feature_subsets.RData')

# avg MI subset matrices 
# bind matrices
x_combined = do.call(cbind, list(data.matrix(x1),data.matrix(x2),data.matrix(x3),data.matrix(x4),data.matrix(x5)))
# recast the matrix into three dimensions
dim(x_combined) <- c(1213,dim(x1)[2],5) 
# now average feature values 
avg_x = apply(x_combined, c(1,2), mean)

# convert back to data.frame
avg_x = as.data.frame(avg_x)
colnames(avg_x) = colnames(x1)
save(avg_x, file = 'avg_subset.RData')


#### FINAL CLUSTERING SCHEMA ####

'''
5 separate clustering results were generated by the MI datasets. For each imputed dateset:
   (1) generate a dissimiliarity matrix
   (2) cluster the observations, assign cluster labels
   (3) for each observation, the most frequent cluster label in the 5 imputed datasets will be 
       the final cluster assignment
   (4) Average the dissimilarity matrices from step (1) to get final averaged dissimilarity matrix
'''

# Step 1

# Make dissimilarity matrices 
gower_dist_matrix_x1 = as.matrix(daisy(x1, metric = 'gower', warnBin = FALSE))
gower_dist_matrix_x2 = as.matrix(daisy(x2, metric = 'gower', warnBin = FALSE))
gower_dist_matrix_x3 = as.matrix(daisy(x3, metric = 'gower', warnBin = FALSE))
gower_dist_matrix_x4 = as.matrix(daisy(x4, metric = 'gower', warnBin = FALSE))
gower_dist_matrix_x5 = as.matrix(daisy(x5, metric = 'gower', warnBin = FALSE))

save(gower_dist_matrix_x1, gower_dist_matrix_x2, gower_dist_matrix_x3, gower_dist_matrix_x4, gower_dist_matrix_x5, file='gower_matrices_20191102.RData')

# Step 2 

# Make PAM clustering objects, extract cluster labels from each object and concatenate into new 
# df 'cluster assignments'

pam_obj1 = cluster_final(gower_dist_matrix_x1)
pam_obj2 = cluster_final(gower_dist_matrix_x2)
pam_obj3 = cluster_final(gower_dist_matrix_x3)
pam_obj4 = cluster_final(gower_dist_matrix_x4)
pam_obj5 = cluster_final(gower_dist_matrix_x5)

cluster_assignments = cbind(pam_obj1$clustering, pam_obj2$clustering, pam_obj3$clustering,pam_obj4$clustering, pam_obj5$clustering)

# Step 3

# Take the most frequent (mode) cluster assignment for each observation as its final cluster label
cluster_labels = factor(apply(cluster_assignments, 1, Mode))

# Step 4
# Average the 5 dissimiliarity matrices to get final averaged dissimilarity matrix

#bind matrices together
gower_m_combined = do.call(cbind, list(gower_dist_matrix_x1, gower_dist_matrix_x2, gower_dist_matrix_x3, gower_dist_matrix_x4, gower_dist_matrix_x5))
#recast the matrix into three dimensions
dim(gower_m_combined) <- c(1213,1213,5) 
#now apply should work
avg_gower_matrix = apply(gower_m_combined, c(1,2), mean)

# Save results
save(avg_gower_matrix, cluster_labels, file = 'avg_clustering_results.RData')

#### Table 1 ####
# training gamma
y_df = cbind(
  unlist(results1[11:15]),
  unlist(results2[11:15]),
  unlist(results3[11:15]),
  unlist(results4[11:15]),
  unlist(results5[11:15])
)

rowMeans(y_df)

# selected features
for(i in c(6:10)){
  print(length(Reduce(intersect, list(results1[[i]], results2[[i]], results3[[i]], results4[[i]], results5[[i]]))))
}

# training k 
traink_df = cbind(
  unlist(results1[31:35]),
  unlist(results2[31:35]),
  unlist(results3[31:35]),
  unlist(results4[31:35]),
  unlist(results5[31:35])
)
apply(traink_df, 1, Mode)


# training SW 
trainsw_df = cbind(
  unlist(results1[36:40]),
  unlist(results2[36:40]),
  unlist(results3[36:40]),
  unlist(results4[36:40]),
  unlist(results5[36:40])
)
rowMeans(trainsw_df)

# training Similarity %
mean(CompSimMat(SimMatrix(results1[[5]]), SimMatrix(cluster_labels[names(cluster_labels) %in% names(results1[[5]])])),
     CompSimMat(SimMatrix(results2[[5]]), SimMatrix(cluster_labels[names(cluster_labels) %in% names(results2[[5]])])),
     CompSimMat(SimMatrix(results3[[5]]), SimMatrix(cluster_labels[names(cluster_labels) %in% names(results3[[5]])])),
     CompSimMat(SimMatrix(results4[[5]]), SimMatrix(cluster_labels[names(cluster_labels) %in% names(results4[[5]])])),
     CompSimMat(SimMatrix(results5[[5]]), SimMatrix(cluster_labels[names(cluster_labels) %in% names(results5[[5]])]))
)

# test Silhouette Width
testsw_df = cbind(
  unlist(results1[21:25]),
  unlist(results2[21:25]),
  unlist(results3[21:25]),
  unlist(results4[21:25]),
  unlist(results5[21:25])
)
rowMeans(trainsw_df)

# testing Similarity %
mean(CompSimMat(SimMatrix(results1[[30]]), SimMatrix(cluster_labels[names(cluster_labels) %in% names(results1[[30]])])),
     CompSimMat(SimMatrix(results2[[30]]), SimMatrix(cluster_labels[names(cluster_labels) %in% names(results2[[30]])])),
     CompSimMat(SimMatrix(results3[[30]]), SimMatrix(cluster_labels[names(cluster_labels) %in% names(results3[[30]])])),
     CompSimMat(SimMatrix(results4[[30]]), SimMatrix(cluster_labels[names(cluster_labels) %in% names(results4[[30]])])),
     CompSimMat(SimMatrix(results5[[30]]), SimMatrix(cluster_labels[names(cluster_labels) %in% names(results5[[30]])]))
)

####

#### Figure 3A ####

# Generate T-SNE object
tsne_obj <- Rtsne(avg_gower_matrix, is_distance = TRUE, perplexity = 50)
tsne_data <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = cluster_labels)

# Plot T-SNE
plot = ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster_labels)) + labs(color = "Cluster") +theme(plot.title = element_text(size = 9)) + 
  scale_color_manual(labels = c('Phenotype A', 'Phenotype B', 'Phenotype C'), values=c("#008EA0FF", "#C71000FF", "#8A4198FF"))+ theme_bw() + theme(legend.title = element_blank()) 


plot ### FIGURE 3A
save(tsne_obj, tsne_data, file = 'tsne_object.RData')

